package com.example.maatjes.models;

public enum Availability {
    MAANDAGOCHTEND,
    MAANDAGMIDDAG,
    MAANDAGAVOND,
    DINSDAGOCHTEND,
    DINSDAGMIDDAG,
    DINSDAGAVOND,
    WOENSDAGOCHTEND,
    WOENSDAGMIDDAG,
    WOENSDAGAVOND,
    DONDERDAGOCHTEND,
    DONDERDAGMIDDAG,
    DONDERDAGAVOND,
    VRIJDAGOCHTEND,
    VRIJDAGMIDDAG,
    VRIJDAGAVOND,
    ZATERDAGOCHTEND,
    ZATERDAGMIDDAG,
    ZATERDAGAVOND,
    ZONDAGOCHTEND,
    ZONDAGMIDDAG,
    ZONDAGAVOND
}
